Ecommerce/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('', views.cart_summary, name="Cart_summary"),
    path('add/', views.cart_add, name="Cart_add"),
    path('remove/<int:product_id>', views.cart_remove, name="Cart_remove"),
    path('update/<int:product_id>', views.cart_update, name="Cart_update"),
]

Ecommerce/Cellestial/urls.py
from django.urls import path
from . import views

app_name = 'Cellestial'

urlpatterns = [
    path('login/', views.login, name="Login"),
    path('logout/', views.logout, name="Logout"),
    path('Register/', views.register, name="Register"),

    path('',views.home,name="Home"),
    path('About/', views.about, name="About"),
    path('Contact/', views.contact, name="Contact"),
    path('Terms-and-Conditions/', views.ToC, name="ToC"),
    path('Shop/', views.shop, name="Shop"),
    path('Product/<int:pk>/', views.product, name="Product"),
    
    path('Shipping/', views.shipping, name="Shipping"),
    path('Payment/', views.payment, name="Payment"),
]       

Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Cellestial.urls')),
    path('Cart/', include('Cart.urls')),
    path('admin/', admin.site.urls),
       
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/Cellestial/models.py
from django.db import models
import datetime

class Customer(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    password = models.CharField(max_length=100)

class Category(models.Model):
    name = models.CharField(max_length=100)

    verbose_name_plural = 'Categories'
    
    def __str__ (self):
        return self.name
    
    
class Color(models.Model):
    name = models.CharField(max_length=100)

    def __str__ (self):
        return self.name
    
class Storage(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField(default=2500)

    def __str__ (self):
        return self.name
    


class Phone(models.Model):
    image = models.ImageField(upload_to='uploads/products/')
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField(default=7999)
    description = models.CharField(max_length=256, default='', blank=True, null=True)
    color = models.ManyToManyField(Color)
    storage = models.ManyToManyField(Storage)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)

    def save(self, *args, **kwargs):
        if self.is_sale:
            self.category = Category.objects.get(name='Discounts')
        super().save(*args, **kwargs)


class Order(models.Model):
    phone = models.ForeignKey(Phone, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    address = models.CharField(max_length=200, blank=True, null=True)
    date_ordered = models.DateTimeField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.customer.name}"

Ecommerce/Cellestial/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="Email", widget=forms.TextInput(attrs={'class':'input', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="First Name", max_length=100, widget=forms.TextInput(attrs={'class':'input', 'placeholder':'First Name', 'id':'half'}))
	last_name = forms.CharField(label="Last Name", max_length=100, widget=forms.TextInput(attrs={'class':'input', 'placeholder':'Last Name', 'id':'half'}))

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email',  'username', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'input'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = 'Username'
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'input'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = 'Password'
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'input'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = 'Confirm Password'
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

Ecommerce/Cellestial/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login, logout as logout_user
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template import loader
from django.urls import reverse
from django import forms
from . import models, forms

# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            auth_login(request, user)
            messages.success(request, 'welcome back' + username)
            return HttpResponseRedirect(reverse('Cellestial:Home'))
        else:
            messages.error(request, 'Username or password is incorrect')
    else:
        return render(request, 'login.html', {})

def logout(request):
    logout_user(request)
    messages.success(request, 'User logged out')
    return redirect('Cellestial:Home')

def register(request):
    form = forms.SignUpForm()
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('Cellestial:Home')
        else:
            return render(request, 'register.html', {'form': form})
    else:
        return render(request, 'register.html', {'form': form})

# MAIN
def home(request):
    return render(request, 'homepage.html', {})

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def ToC(request):
    return render(request, 'terms_and_con.html')

def shop(request):  
    try:
        products = models.Phone.objects.all()
        return render(request, 'shop.html', {'products': products})
    except Exception as e:
        messages.error(request, f'An error occurred while fetching products: {e}')
        return render(request, 'shop.html', {})

# Product Detail    
def product(request, pk):
    product = models.Phone.objects.get(id=pk)
    storage = product.storage.all()
    for each in storage:
        each.price += product.price
    context = {
        'product': product,
        'storage': storage,
        'color' : product.color.all(),
    }
    return render(request, 'details.html', context)

# Checkouts
def shipping(request):
    return render(request, 'shipping.html')

def payment(request):
    return render(request, 'payment.html')

Ecommerce/Cellestial/templates/details.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    {{product.name}}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/details.css' %}">

{% endblock %}

{% block content %}
    <div class="container">
        <div class="left-section">
            <div class="title-container">
                <h1 class="title">{{ product.name }}</h1>
                <p class="subtitle">{{product.description}}</p>
            </div>
            <div class="image-gallery">
                <div class="main-image">
                    <img src="{{product.image.url}}" alt="Main Image" id="mainImage">
                </div>
            </div>

            <div class="horizontal-images">
                <img src="{{product.image.url}}" alt="{{product.name}}" class="phones" onmouseover="changeImage(this)"> 
                <img src="{{product.image.url}}" alt="{{product.name}}" class="phones" onmouseover="changeImage(this)">
                <img src="{{product.image.url}}" alt="{{product.name}}" class="phones" onmouseover="changeImage(this)">
            </div>


            <div class="options-section">
                <h2>Color</h2>
                <div class="colors" id="colorOptions">
                    {% for c in color %}
                    <div class="color-circle option" data-color="{{ c.name }}" onclick="selectOption('colorOptions', this)"></div>
                    {% endfor %}
                </div>
            </div>            
        </div>

        <div class="product-details">
            <div class="button">Get 3% Daily Cashback with Interstellar Pass</div>

                <div class="options-section">
                    <h2>Find the Model That Suits Your Style</h2>
                    <div class="model-options" id="modelOptions">
                        <div class="model-option option" onclick="selectOption('modelOptions', this)">
                            <div class="details">
                                <strong>{{product.name}} Zero</strong>
                                <span>6 inch display</span>
                            </div>
                            <span>From ₱37,499 <br> or ₱1,562.42/mo <br> for 24 months</span>
                        </div>
                        <div class="model-option option" onclick="selectOption('modelOptions', this)">
                            <div class="details" >
                                <strong>{{product.name}}</strong>
                                <span>6 inch display</span>
                            </div>
                            <span>From ₱{{product.price}} <br> or ₱1,729.12/mo <br> for 24 months</span>
                        </div>
                        <div class="model-option option" onclick="selectOption('modelOptions', this)">
                            <div class="details">
                                <strong>Prestige {{product.name}}</strong>
                                <span>6.9 inch display</span>
                            </div>
                            <span>From ₱59,999 <br> or ₱2,500/mo for <br> 24 months</span>
                        </div>
                    </div>

                    <div class="options-section storage-options">
                    <h2>Storage Options</h2>
                    <div class="model-options" id="storageOptions">
                        {% for storage in storage %}                        
                        <div class="model-option option" onclick="selectOption('storageOptions', this)">
                            <div class="details " >
                                <strong>{{storage.name}}</strong>
                            </div>
                            <span>For ₱{{storage.price}}</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    <section class="trade-in-section">
        <h2>Celestial </h2>
        <div class="trade-in-buttons" id="tradeOptions">
            <button type='button'class="yes option" id="addToCart" value="{{product.id}}">
                Add To Cart
            </button>
            <button class="no option" onclick="selectOption('tradeOptions', this)">
                Check Out
            </button>
        </div>
    </section>

    <section id="payment-options">
        <h2>Choose your Payment option</h2>
        <div class="options-container" id="onetimeOptions">
            <div class="payment option" onclick="selectOption('onetimeOptions', this)">
                <h3>One-time payment</h3>
                <p>₱{{storage.price}}</p>
            </div> 
            <div class="payment option" onclick="selectOption('onetimeOptions', this)">
                <h3>Celestial Financing (Pay Monthly)</h3>
                <p>₱1,729.12/mo<br>for 24 months</p>
            </div>
            <div class="payment option" onclick="selectOption('onetimeOptions', this)">
                <h3>One-time payment</h3>
                <p>₱864.56<br>every 2 weeks</p>
            </div>
        </div>
        
    
        <div class="one-time" >
            <div class="one-time-content">
                <img src="{% static 'images/credit-card.jpg' %}" alt="Credit Card" class="credit-card-image">
                <div class="one-time-text">
                    <h3>One-time payment</h3>
                    <p>Pay with your credit card, debit card, or a pay app. Excludes taxes and shipping.</p>
                </div>
            </div>
        </div>
        
        
    
        <div class="payment-details" >
            <div class="anada-details">
                <div class="price-item">
                    <span class="penex"><strong>PhoenixRise Zero</strong></span>
                    <span class="forty-one"><strong>₱41, 999</strong></span>
                </div>
                <p>512 GB | Midnight Express</p>
                <br>
                <div class="store-content">
                    <img src="{% static 'images/store.png' %}" alt="Store" class="store-image">
                        <div class="store-text">
                            <p>In-store pickup:</p>
                            <p><a href="#">Select store</a></p>
                        </div>
                </div>
                <div class="delivery-content">
                    <img src="{% static 'images/deliver.png' %}" alt="Store" class="delivery-image">
                        <div class="delivery-text">
                            <p>Delivery for <a href="#">4327</a></p>
                        </div>
                </div>
            <div class="get-it">
                    <p>Get it by Nov. 2024</p>
            </div> 
        </div>
            
        <br>
        <hr>
    
    
            <div class="pricing">
                <div class="price-item">
                    <span>Instant Savings:</span>
                    <span>₱1,200</span>
                </div>
                <hr>
                <div class="price-item">
                    <span><strong>Total:</strong></span>
                    <span>₱40,799</span>
                </div>
                <div class="price-item">
                    <span><strong>You Saved Today:</strong></span>
                    <span>₱1,200</span>
                </div>
            </div>
            <hr>
            <div class="button-container">
                <button class="continue-button">Continue</button>
            </div>
    </section>


{%endblock%}

{% block scripts %}
    <script>
        $(document).on('click', '#addToCart', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "Cart:Cart_add" %}',
                data: {
                    product_id: $('#addToCart').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },

                success: function(json) {
                    console.log(json);
                },

                error: function(xhr, errmsg, err) {
                }
            });
        });
    </script>
    <script src="{% static 'js/details.js' %}"></script>
{% endblock %}

Ecommerce/Cellestial/templates/login.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    Login
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
        <!-- Nunito Font: Alternative for ABeeZee Font  -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=League+Spartan:wght@100..900&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="left-container">
    <div class="centerdiv">
        <div class="content">
            <h1>Welcome to Cellestial!</h1>
            <p>Unlock the future today. It's your moment. Shape it with innovation. Sign in to explore and manage your devices.</p>
        </div>
        <form action="{% url 'Cellestial:Login' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" name="username" id="username" placeholder="Username">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" placeholder="Password">
            </div>
            <div class="action-buttons">
                <a onclick = "windw.alert('Womp Womp🐳?')">Forgot password?</a>
                <button type="submit" class="submit" name="sign_in">Login</button>
                <p>Don't have an account? <a href="{% url 'Cellestial:Register'%}">Register</a></p>
            </div>
        </form>
        <hr>
        <div class="continue">
            <button>
                <img src="{% static 'google.png' %}" alt="">
                Sign in with Google
            </button>
            <button>
                <img src="{% static 'facebook.png' %}" alt="">
                Sign in with Facebook
            </button>
            <button>
                <img src="{% static 'apple.png' %}" alt="">
                Sign in with Apple
            </button>
        </div>
        <h4> © 2024 CELLESTIAL</h4>
    </div>
</div>

<div class="right-container">
    <img src="{% static 'log/login.png' %}" alt="Phone in hand">                    
</div>
        

{% endblock %}

Ecommerce/Cellestial/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>{%block title%}{%endblock%} | Cellestial</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&family=Actor&family=Inika:wght@400;700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Irish+Grover&family=Khand:wght@300;400;500;600;700&family=Marcellus+SC&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">

    <base href="../../static/">
    <link rel="icon" href="favicon.ico" />
    <link rel="stylesheet" type="text/css" href="css/main.css">

    <!-- add to cart -->
    <script
        src="https://code.jquery.com/jquery-3.7.1.min.js" 
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" 
        crossorigin="anonymous">
    </script>
    
    {%block head%}
    
    {%endblock%}
</head>

<body>
    <header>
        <div class="logo-container">
            <a href="/" class="logo-text">
                <img src="LOGO.png" alt="Cellestial" class="logo-img" />
                <p class="logo-text">Cellestial</p>                
            </a>
        </div>
    
        <div class="search-container">
            <input type="text" class="search-bar" placeholder="Search..." />
            <i class="bx bx-search"></i>
    
            <div class="search-dropdown">
              <a href="/">Home</a>
              <a href="{% url 'Cellestial:Shop' %}">Shop</a>
              <a href="{% url 'Cellestial:Shipping'%}">Check Shipping</a>
              <a href="/brands">Brands</a>
            </div>
        </div>
    
    
          <input aria-label="bx bx-menu" type="checkbox" name="" id="toggler" />
    
    
        <div class="icons">
            <div>
                <a title="Wishlist" href="/#">
                    <i class="bx bxs-heart"></i> 
                </a>
            </div>
            <div>
                <a title="Cart" href="{% url 'Cart:Cart_summary' %}"><i class="bx bxs-cart"></i></a>
            </div>
            {% if user.is_authenticated %}
            <div class="account-menu">
                <a title="User" href="{% url 'Cellestial:Register' %}"><i class="bx bxs-user"></i> {{request.user.username}}</a>
                <div class="extension">
                    <a title="Logout" href="{% url 'Cellestial:Logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a>
                </div>
            </div>
            {% else %}
            <div>
                <a title="Login" href="{% url 'Cellestial:Login' %}"><i class="bx bxs-user"></i></a>
            </div>
            {% endif %}
        </div>
    </header>
    <main>
        {%block content%}
    
        {%endblock%}
    </main>
    <footer class="footer">
        <div class="footer-column">
            <h1>Cellestial</h1>
            <p>Empower your lifestyle with the latest tech. From smartphones to smart homes, we’ve got you covered. Shop with confidence.</p>
            <div class="footer-social">
                <a aria-label="Twitter" href="https://twitter.com"><i class="fa-brands fa-twitter"></i></a>
                <a aria-label="Facebook" href="https://facebook.com"><i class="fab fa-facebook-f"></i></a>
                <a aria-label="Instagram" href="https://instagram.com"><i class="fab fa-instagram"></i></a>
                <a aria-label="Apple" href="https://apple.com"><i class="fab fa-apple"></i></a>
            </div>
        </div>
        <div class="footer_container">
            <div class="footer-column">
                <h3>Company</h3>
                <ul>
                    <li><a href="{% url 'Cellestial:About' %}" target="_blank">About</a></li>
                    <li><a href="#">Features</a></li>
                    <li><a href="#">Works</a></li>
                    <li><a href="#">Career</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Help</h3>
                <ul>
                    <li><a href="{% url 'Cellestial:Contact' %}" target="_blank">Contact us</a></li>
                    <li><a href="#">Delivery Details</a></li>
                    <li><a href="{% url 'Cellestial:ToC'%}" target="_blank">Terms & Conditions</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>FAQ</h3>
                <ul>
                    <li><a href="#">Account</a></li>
                    <li><a href="#">Manage Deliveries</a></li>
                    <li><a href="#">Orders</a></li>
                    <li><a href="#">Payments</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Resources</h3>
                <ul>
                    <li><a href="#">Vouchers</a></li>
                    <li><a href="#">E-shipping</a></li>
                    <li><a href="#">Other Services</a></li>
                </ul>
            </div>
        </div>
    </footer>
    <div class="footer-bottom">
        <hr class="footer-divider">
        <div class="footer-bottom-container">
            <p>Cellestial © 2024 All Rights Reserved</p>
            <div class="payment-methods">
                <i class="fa-brands fa-cc-visa"></i>
                <i class="fa-brands fa-cc-paypal"></i>
                <i class="fa-brands fa-cc-apple-pay"></i>
                <i class="fa-brands fa-google-pay"></i>
            </div>
        </div>
    </div>
    {% block scripts%}
    
    {%endblock%}
</body>
</html>

Ecommerce/Cellestial/templates/register.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    Register
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <!-- Nunito Font: Alternative for ABeeZee Font  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=League+Spartan:wght@100..900&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}


<!-- Left Container (Image) -->
<div class="left-container">
    <img src="{% static 'signuppic.png'%}" alt="Sign Up Illustration">
</div>

<div class="right-container">
    <div class="center-content">
        <div class="content">
            <h1>Create Your Account</h1>
            <p>Start your journey with us. It only takes a few steps!</p>
        </div>
        <form action="{% url 'Cellestial:Register' %}" method="POST">  
            {% csrf_token %}
            <div class="input-groups">
                {% for field in form %}
                    <div class="input-field">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
            <div class="action-buttons">
                <button type="submit" class="submit">Sign Up</button>
                <p>Already have an account? <a href="{% url 'Cellestial:Login' %}">Login</a></p>
            </div>
        </form>
    </div>
</div>


{% endblock %}

Ecommerce/Cellestial/templates/shop.html
{% extends 'master.html' %}
{% load static %}

{% block title %}
    Products
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/shop.css' %}">
{%endblock%}

{% block content %}
    <!-- Mobile Picks Section -->
    <section class="mobile-picks">
        <h2>Sparkling savings that'll have you smiling</h2>
        <div class="categories">
            <a id="for-you">For You</a>
            <a id="hot-deals">Hot Deals</a>
            <a id="brand-new">Brand New</a>
            <a id="discounts">Discounts</a>
        </div>
        <div class="main-content">
            <div id="for-you-content" >
                <div class="product-grid">
                    {% for product in products %}
                        {% if product.category.name == 'For You' %}
                            <div class="product">
                                <img src="{{ product.image.url }}"  alt="Product 1">
                                <p class="deal">{{product.name}}</p>
                                <p class="product-price">₱{{product.price}}</p>
                                <a href="{% url 'Cellestial:Product' product.id %}">
                                    <button>BUY NOW</button>
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
    
            <div id="hot-deals-content" hidden>
                <div class="product-grid">
                    {% for product in products %}
                        {% if product.category.name == 'Hot Deals' %}
                    <div class="product">
                        <img src="{{ product.image.url }}"  alt="Product 1">
                        <p class="deal">{{product.name}}</p>
                        <p class="product-price">₱{{product.price}}</p>
                        <a href="{% url 'Cellestial:Product' product.id %}">
                            <button>BUY NOW</button>
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
    
            <div id="brand-new-content" hidden>
                <div class="product-grid">
                    {% for product in products %}
                        {% if product.category.name == 'Brand New' %}
                    <div class="product">
                        <img src="{{ product.image.url }}"  alt="Product 1">
                        <p class="deal">{{product.name}}</p>
                        <p class="product-price">₱{{product.price}}</p>
                        <a href="{% url 'Cellestial:Product' product.id %}">
                            <button>BUY NOW</button>
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>    
    
            <div id="discounts-content" hidden >
                <div class="product-grid">
                    {% for product in products %}
                        {% if product.category.name == 'Discounts' %}
                    <div class="product">
                        <img src="{{ product.image.url }}"  alt="Product 1">
                        <p class="deal">{{product.name}}</p>
                        <p class="product-price">
                            <strike>₱{{product.price}}</strike>
                            &nbsp;
                            ₱{{product.sale_price}}
                        </p>
                        
                        <a href="{% url 'Cellestial:Product' product.id %}">
                            <button>BUY NOW</button>
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

{%endblock%}

{% block script %}
    <script src="{% static 'js/shop.js' %}"></script>
{% endblock %}